const express = require('express');
const router = express.Router();
const videoUploadController = require('../../controllers/videoUpload');
const videoMiddleware = require('../../middlewares/vid');
const ImageMiddleware = require('../../middlewares/image');
router.route('/:id').post(videoMiddleware, videoUploadController.Upload_Videos);
router.route('/content').get(videoUploadController.contentUpload);
router.route('/get/All').get(videoUploadController.getAllData);
router.route('/image/upload/:id').post(ImageMiddleware, videoUploadController.Upload_Image);
router.route('/').post(videoUploadController.createNewData);
router.route('/updateDataById/:id').put(videoUploadController.updateDataById);
module.exports = router;
